// Completely synthetic demo data. Every organization, person, project, and source below is fictional.

export type NodeKind =
  | "company"
  | "capital"
  | "government"
  | "institution"
  | "person"
  | "project";

export type EdgeKind =
  | "supply"
  | "capital"
  | "governance"
  | "research"
  | "certification"
  | "support"
  | "delivery"
  | "circular";

export interface DemoNode {
  id: string;
  name: string;
  kind: NodeKind;
  subtitle: string;
  x: number;
  y: number;
  z: number;
  summary: string;
  metric: string;
  risk: "high" | "medium" | "low";
  status: "verified" | "review" | "planned";
  sources: string[];
}

export interface DemoEdge {
  id: string;
  source: string;
  target: string;
  kind: EdgeKind;
  label: string;
  weight: number;
  status: "verified" | "review";
  evidenceId: string;
  evidence: string;
  sourceTitle: string;
  location: string;
  confidence: number;
  directed: boolean;
}

export interface DemoScene {
  id: string;
  title: string;
  subtitle: string;
  viewMode?: "2d" | "3d";
  layout: "force" | "radial" | "layered";
  selectedId: string;
  selectedEdgeId?: string;
  visibleNodes?: string[];
  visibleKinds?: EdgeKind[];
  callout: string;
}

type DemoSource = {
  id: string;
  title: string;
  date: string;
  type: "Corporate Materials" | "Agreement" | "Project File" | "Testing Report" | "Policy Document" | "Analytical Workpaper";
  summary: string;
};

export const DEMO_SOURCES: DemoSource[] = [
  {
    id: "S01",
    title: "Jichuan Power 2025 Operating Brief",
    date: "2026-02-28",
    type: "Corporate Materials",
    summary: "Discloses Jichuan Power's capacity, revenue, management, major customers, and control-system coverage.",
  },
  {
    id: "S02",
    title: "Jichuan Power Shareholders and Related Parties Register",
    date: "2026-01-31",
    type: "Corporate Materials",
    summary: "Lists major shareholders, management equity interests, research-institute affiliations, and annual R&D investment.",
  },
  {
    id: "S03",
    title: "Three-Year Core Raw Materials Procurement Framework",
    date: "2025-09-12",
    type: "Agreement",
    summary: "Summarizes supplier shares and contract terms for lithium salts, cathode materials, and copper foil.",
  },
  {
    id: "S04",
    title: "Xingyu–Chengyue Supply Agreement Summary",
    date: "2025-08-30",
    type: "Agreement",
    summary: "Defines Xingyu Lithium's minimum share of lithium-salt supply to Chengyue Advanced Materials.",
  },
  {
    id: "S05",
    title: "Yaotu–Jichuan Annual Procurement Agreement",
    date: "2025-11-05",
    type: "Agreement",
    summary: "Sets the annual procurement volume for new energy commercial-vehicle traction batteries.",
  },
  {
    id: "S06",
    title: "Haiyu Energy Storage Cell Procurement Framework",
    date: "2026-01-08",
    type: "Agreement",
    summary: "Sets Haiyu Energy Storage's 2026 framework allocation for stationary-storage cells.",
  },
  {
    id: "S07",
    title: "Battery Recycling Closed-Loop Cooperation Memorandum",
    date: "2026-02-11",
    type: "Agreement",
    summary: "Describes end-of-life battery transfers and the target for return supply of recycled lithium salts.",
  },
  {
    id: "S08",
    title: "Jiaxu Capital New Energy Portfolio Review",
    date: "2026-01-10",
    type: "Corporate Materials",
    summary: "Discloses Jiaxu Capital's new energy holdings, management team, and anchor institutional investor.",
  },
  {
    id: "S09",
    title: "Joint R&D Agreement and Patent Ownership Schedule",
    date: "2025-08-22",
    type: "Agreement",
    summary: "Records joint R&D arrangements for BMS algorithms and high-manganese phosphate cathode materials.",
  },
  {
    id: "S10",
    title: "Anlan Testing Certification Report AL-26-017",
    date: "2026-03-01",
    type: "Testing Report",
    summary: "Covers safety and fault-degradation testing for stationary-storage cells, battery packs, and BMS.",
  },
  {
    id: "S11",
    title: "Donglan New Energy Special Funding Disclosure — Batch I",
    date: "2026-02-05",
    type: "Policy Document",
    summary: "Discloses special funding awarded to the Beigang zero-carbon logistics and Qingyu shared-storage projects.",
  },
  {
    id: "S12",
    title: "Beigang Zero-Carbon Logistics Demonstration Project Implementation Plan",
    date: "2026-01-15",
    type: "Project File",
    summary: "Sets out project scale, vehicles, charging stations, suppliers, and operating responsibilities.",
  },
  {
    id: "S13",
    title: "Qingyu Shared Energy Storage Phase I Feasibility Study Summary",
    date: "2025-12-20",
    type: "Project File",
    summary: "Sets out storage capacity, investment, planned commissioning, and principal delivery parties.",
  },
  {
    id: "S14",
    title: "Supply Chain Stress Test and Substitutability Assessment",
    date: "2026-03-22",
    type: "Analytical Workpaper",
    summary: "Assesses substitution lead times, criticality scores, and network centrality for key suppliers.",
  },
  {
    id: "S15",
    title: "New Energy Ecosystem Entity Verification Register",
    date: "2026-03-25",
    type: "Analytical Workpaper",
    summary: "Consolidates upstream capacity, downstream delivery scale, fund size, and institutional capabilities.",
  },
];

export const DEMO_NODES: DemoNode[] = [
  {
    id: "N01",
    name: "Jichuan Power",
    kind: "company",
    subtitle: "Core manufacturer of traction and stationary-storage cells",
    x: 0,
    y: 0,
    z: 0,
    summary: "The ecosystem's single-core hub, linking upstream materials, control systems, capital, and two end-use segments.",
    metric: "24 GWh · Revenue RMB 4.86bn",
    risk: "high",
    status: "verified",
    sources: ["S01", "S02", "S14"],
  },
  {
    id: "N02",
    name: "Xingyu Lithium",
    kind: "company",
    subtitle: "Battery-grade lithium supplier",
    x: -25,
    y: 12,
    z: -4,
    summary: "Supplies both Jichuan Power and Chengyue Advanced Materials, with a long substitution lead time.",
    metric: "Capacity 45,000 t · Criticality 4.6",
    risk: "high",
    status: "verified",
    sources: ["S03", "S04", "S14", "S15"],
  },
  {
    id: "N03",
    name: "Chengyue Advanced Materials",
    kind: "company",
    subtitle: "Cathode active-material supplier",
    x: -17,
    y: 5,
    z: 2,
    summary: "Jichuan Power's largest cathode-material source and a pilot-scale partner for next-generation materials.",
    metric: "Capacity 120,000 t · Procurement share 44%",
    risk: "high",
    status: "verified",
    sources: ["S03", "S09", "S14", "S15"],
  },
  {
    id: "N04",
    name: "Hengling Copper Foil",
    kind: "company",
    subtitle: "Battery-grade copper foil supplier",
    x: -20,
    y: -7,
    z: -2,
    summary: "Supplies traction-battery copper foil to Jichuan Power, with a moderate level of concentration.",
    metric: "Capacity 65,000 t · Procurement share 31%",
    risk: "medium",
    status: "verified",
    sources: ["S03", "S15"],
  },
  {
    id: "N05",
    name: "Lanxin Intelligent Controls",
    kind: "company",
    subtitle: "BMS, EMS, and PCS provider",
    x: -2,
    y: 14,
    z: 5,
    summary: "Spans battery production, logistics charging infrastructure, and shared-storage projects, making it a critical control-systems node.",
    metric: "Covers 62% of battery packs in production",
    risk: "high",
    status: "verified",
    sources: ["S01", "S08", "S09", "S10", "S14"],
  },
  {
    id: "N06",
    name: "Yaotu Commercial Vehicles",
    kind: "company",
    subtitle: "New energy commercial-vehicle OEM",
    x: 21,
    y: 8,
    z: 4,
    summary: "Jichuan Power's largest traction-battery framework customer and the vehicle supplier to the Beigang project.",
    metric: "Annual capacity 28,000 vehicles",
    risk: "medium",
    status: "verified",
    sources: ["S05", "S12", "S15"],
  },
  {
    id: "N07",
    name: "Haiyu Energy Storage",
    kind: "company",
    subtitle: "Battery energy storage system integrator",
    x: 20,
    y: -5,
    z: 0,
    summary: "Serves as system integrator for Qingyu and holds a framework allocation for Jichuan stationary-storage cells.",
    metric: "Cumulative deliveries 2.1 GWh",
    risk: "medium",
    status: "verified",
    sources: ["S06", "S08", "S13", "S15"],
  },
  {
    id: "N08",
    name: "Xunguang Resources",
    kind: "company",
    subtitle: "End-of-life battery recycler",
    x: -11,
    y: -16,
    z: 5,
    summary: "Takes Jichuan's end-of-life batteries and plans to close the materials loop through recycled lithium-salt supply.",
    metric: "Recycling capacity 50,000 t/year",
    risk: "medium",
    status: "verified",
    sources: ["S07", "S15"],
  },
  {
    id: "N09",
    name: "Yuncang Logistics",
    kind: "company",
    subtitle: "Commercial fleet operator",
    x: 25,
    y: 16,
    z: -3,
    summary: "Responsible for five years of fleet operations at Beigang and a direct indicator of project demand realization.",
    metric: "Fleet under operation 18,000 vehicles",
    risk: "low",
    status: "verified",
    sources: ["S12", "S15"],
  },
  {
    id: "N10",
    name: "Jiaxu Capital",
    kind: "capital",
    subtitle: "New energy investment firm",
    x: 0,
    y: -21,
    z: 7,
    summary: "Investments across cells, control systems, and storage integration create cross-segment capital influence paths.",
    metric: "Assets under management RMB 12bn",
    risk: "medium",
    status: "verified",
    sources: ["S02", "S08", "S15"],
  },
  {
    id: "N11",
    name: "Donglan Industrial Guidance Fund",
    kind: "capital",
    subtitle: "Government-backed industrial guidance fund",
    x: -9,
    y: -29,
    z: 2,
    summary: "A direct investor in Jichuan Power and the anchor institutional investor in Jiaxu Capital's new-energy investment platform.",
    metric: "Fund size RMB 20bn",
    risk: "low",
    status: "verified",
    sources: ["S02", "S08", "S15"],
  },
  {
    id: "N12",
    name: "Jichuan Advanced Battery Research Institute",
    kind: "institution",
    subtitle: "Joint R&D platform for battery technology",
    x: -9,
    y: 22,
    z: 7,
    summary: "Connects Jichuan, Lanxin, and Chengyue, undertaking control-algorithm development and new-material pilot programs.",
    metric: "37 active patents",
    risk: "low",
    status: "verified",
    sources: ["S02", "S09", "S15"],
  },
  {
    id: "N13",
    name: "Anlan Testing Center",
    kind: "institution",
    subtitle: "Battery and grid-connection testing body",
    x: 11,
    y: 22,
    z: -4,
    summary: "Conducts cell and control-system testing and is responsible for grid-connection acceptance at Qingyu.",
    metric: "Covers 3 critical certification categories",
    risk: "low",
    status: "verified",
    sources: ["S10", "S13"],
  },
  {
    id: "N14",
    name: "Donglan New Energy Promotion Bureau",
    kind: "government",
    subtitle: "Industrial development and project funding agency",
    x: 19,
    y: -23,
    z: -3,
    summary: "Provides special funding to both logistics electrification and shared-storage projects.",
    metric: "Special funding RMB 380m",
    risk: "low",
    status: "verified",
    sources: ["S11"],
  },
  {
    id: "N15",
    name: "Shen Yanzhou",
    kind: "person",
    subtitle: "Chairman and CEO, Jichuan Power",
    x: 8,
    y: -13,
    z: 11,
    summary: "Also chairs the research institute, linking corporate governance with R&D resources.",
    metric: "6.5% equity interest",
    risk: "medium",
    status: "verified",
    sources: ["S01", "S02"],
  },
  {
    id: "N16",
    name: "Lin Jianwei",
    kind: "person",
    subtitle: "Managing Partner, Jiaxu Capital",
    x: 4,
    y: -31,
    z: 9,
    summary: "Responsible for portfolio allocation and post-investment management across Jiaxu's new energy holdings.",
    metric: "Coverage across 3 critical ecosystem nodes",
    risk: "low",
    status: "verified",
    sources: ["S08"],
  },
  {
    id: "N17",
    name: "Beigang Zero-Carbon Logistics Demonstration Project",
    kind: "project",
    subtitle: "New energy commercial vehicles and charging network",
    x: 34,
    y: 9,
    z: 8,
    summary: "A regional demonstration project integrating vehicles, batteries, control systems, and fleet operations.",
    metric: "RMB 1.8bn · 1,200 vehicles · 48 stations",
    risk: "medium",
    status: "planned",
    sources: ["S11", "S12"],
  },
  {
    id: "N18",
    name: "Qingyu Shared Energy Storage Phase I",
    kind: "project",
    subtitle: "Regional shared battery energy storage facility",
    x: 34,
    y: -9,
    z: -7,
    summary: "Integrated by Haiyu, with supply from Jichuan and Lanxin; grid-connection acceptance remains outstanding before commissioning.",
    metric: "200 MW / 400 MWh · RMB 960m",
    risk: "medium",
    status: "planned",
    sources: ["S11", "S13"],
  },
];

export const DEMO_EDGES: DemoEdge[] = [
  {
    id: "E01",
    source: "N02",
    target: "N03",
    kind: "supply",
    label: "Lithium-salt supply · 55%",
    weight: 0.82,
    status: "verified",
    evidenceId: "S04-C1",
    evidence: "For 2025–2027, Xingyu commits to supply no less than 55% of Chengyue's demand for battery-grade lithium salts.",
    sourceTitle: "Xingyu–Chengyue Supply Agreement Summary",
    location: "§2",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E02",
    source: "N02",
    target: "N01",
    kind: "supply",
    label: "Direct lithium-salt supply · 36%",
    weight: 0.86,
    status: "verified",
    evidenceId: "S03-C1",
    evidence: "Xingyu Lithium accounts for approximately 36% of Jichuan Power's annual procurement of battery-grade lithium salts.",
    sourceTitle: "Three-Year Core Raw Materials Procurement Framework",
    location: "p.4",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E03",
    source: "N03",
    target: "N01",
    kind: "supply",
    label: "Cathode-material supply · 44%",
    weight: 0.91,
    status: "verified",
    evidenceId: "S03-C2",
    evidence: "Chengyue Advanced Materials accounts for 44% of Jichuan Power's cathode-material procurement volume.",
    sourceTitle: "Three-Year Core Raw Materials Procurement Framework",
    location: "p.5",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E04",
    source: "N04",
    target: "N01",
    kind: "supply",
    label: "Copper-foil supply · 31%",
    weight: 0.72,
    status: "verified",
    evidenceId: "S03-C3",
    evidence: "Hengling Copper Foil accounts for 31% of Jichuan Power's battery copper-foil procurement volume.",
    sourceTitle: "Three-Year Core Raw Materials Procurement Framework",
    location: "p.5",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E05",
    source: "N05",
    target: "N01",
    kind: "supply",
    label: "BMS controllers · 62% coverage",
    weight: 0.94,
    status: "verified",
    evidenceId: "S01-C2",
    evidence: "Lanxin Intelligent Controls supplies controllers for 62% of Jichuan Power's battery packs in production.",
    sourceTitle: "Jichuan Power 2025 Operating Brief",
    location: "p.7 §3.2",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E06",
    source: "N01",
    target: "N06",
    kind: "supply",
    label: "Traction batteries · 8 GWh/year",
    weight: 0.95,
    status: "verified",
    evidenceId: "S05-C1",
    evidence: "Yaotu plans to procure no less than 8 GWh of commercial-vehicle traction batteries from Jichuan annually.",
    sourceTitle: "Yaotu–Jichuan Annual Procurement Agreement",
    location: "§3",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E07",
    source: "N01",
    target: "N07",
    kind: "supply",
    label: "Stationary-storage cells · 3.2 GWh/year",
    weight: 0.8,
    status: "verified",
    evidenceId: "S06-C1",
    evidence: "Haiyu receives a 2026 framework allocation of up to 3.2 GWh of stationary-storage cells from Jichuan.",
    sourceTitle: "Haiyu Energy Storage Cell Procurement Framework",
    location: "§2",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E08",
    source: "N01",
    target: "N08",
    kind: "circular",
    label: "Priority recycling of end-of-life batteries",
    weight: 0.61,
    status: "verified",
    evidenceId: "S07-C1",
    evidence: "Jichuan will give Xunguang Resources priority for dismantling and processing eligible end-of-life batteries.",
    sourceTitle: "Battery Recycling Closed-Loop Cooperation Memorandum",
    location: "§2",
    confidence: 0.94,
    directed: true,
  },
  {
    id: "E09",
    source: "N08",
    target: "N01",
    kind: "circular",
    label: "Recycled lithium return supply · 20% target",
    weight: 0.48,
    status: "review",
    evidenceId: "S07-C2",
    evidence: "The parties target recycled lithium supplied back by Xunguang to cover 20% of Jichuan's requirements by 2027.",
    sourceTitle: "Battery Recycling Closed-Loop Cooperation Memorandum",
    location: "§4",
    confidence: 0.79,
    directed: true,
  },
  {
    id: "E10",
    source: "N10",
    target: "N01",
    kind: "capital",
    label: "Direct equity interest · 12.4%",
    weight: 0.79,
    status: "verified",
    evidenceId: "S02-C1",
    evidence: "Jiaxu Capital holds a 12.4% equity interest in Jichuan Power.",
    sourceTitle: "Jichuan Power Shareholders and Related Parties Register",
    location: "p.3",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E11",
    source: "N11",
    target: "N01",
    kind: "capital",
    label: "Direct equity interest · 8.0%",
    weight: 0.65,
    status: "verified",
    evidenceId: "S02-C2",
    evidence: "Donglan Industrial Guidance Fund holds an 8.0% equity interest in Jichuan Power.",
    sourceTitle: "Jichuan Power Shareholders and Related Parties Register",
    location: "p.3",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E12",
    source: "N11",
    target: "N10",
    kind: "capital",
    label: "Strategic capital commitment · 24%",
    weight: 0.76,
    status: "verified",
    evidenceId: "S08-C2",
    evidence: "Donglan Industrial Guidance Fund has committed capital equal to 24% of Jiaxu Capital's new-energy investment platform.",
    sourceTitle: "Jiaxu Capital New Energy Portfolio Review",
    location: "p.2",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E13",
    source: "N10",
    target: "N05",
    kind: "capital",
    label: "Direct equity interest · 18%",
    weight: 0.83,
    status: "verified",
    evidenceId: "S08-C1",
    evidence: "Jiaxu Capital holds an 18% equity interest in Lanxin Intelligent Controls.",
    sourceTitle: "Jiaxu Capital New Energy Portfolio Review",
    location: "p.6",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E14",
    source: "N10",
    target: "N07",
    kind: "capital",
    label: "Direct equity interest · 9%",
    weight: 0.62,
    status: "verified",
    evidenceId: "S08-C3",
    evidence: "Jiaxu Capital holds a 9% equity interest in Haiyu Energy Storage.",
    sourceTitle: "Jiaxu Capital New Energy Portfolio Review",
    location: "p.6",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E15",
    source: "N15",
    target: "N01",
    kind: "governance",
    label: "Chairman and CEO · 6.5% equity interest",
    weight: 0.92,
    status: "verified",
    evidenceId: "S01-C1",
    evidence: "Shen Yanzhou serves as Chairman and CEO of Jichuan Power and holds a 6.5% equity interest in the company.",
    sourceTitle: "Jichuan Power 2025 Operating Brief",
    location: "p.2 §1.1",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E16",
    source: "N16",
    target: "N10",
    kind: "governance",
    label: "Managing Partner",
    weight: 0.73,
    status: "verified",
    evidenceId: "S08-C4",
    evidence: "Lin Jianwei serves as Managing Partner of Jiaxu Capital.",
    sourceTitle: "Jiaxu Capital New Energy Portfolio Review",
    location: "p.6",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E17",
    source: "N15",
    target: "N12",
    kind: "governance",
    label: "Chair, Research Institute",
    weight: 0.64,
    status: "verified",
    evidenceId: "S02-C3",
    evidence: "Shen Yanzhou concurrently serves as Chair of the Jichuan Advanced Battery Research Institute.",
    sourceTitle: "Jichuan Power Shareholders and Related Parties Register",
    location: "p.8",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E18",
    source: "N01",
    target: "N12",
    kind: "research",
    label: "R&D funding · RMB 60m/year",
    weight: 0.71,
    status: "verified",
    evidenceId: "S02-C4",
    evidence: "Jichuan Power provides RMB 60 million in annual R&D funding to the research institute.",
    sourceTitle: "Jichuan Power Shareholders and Related Parties Register",
    location: "p.8",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E19",
    source: "N12",
    target: "N05",
    kind: "research",
    label: "Joint development of vehicle-storage coordinated BMS",
    weight: 0.68,
    status: "verified",
    evidenceId: "S09-C1",
    evidence: "The research institute and Lanxin are jointly developing a vehicle-storage coordinated BMS algorithm; the interim prototype is complete.",
    sourceTitle: "Joint R&D Agreement and Patent Ownership Schedule",
    location: "p.3",
    confidence: 0.94,
    directed: true,
  },
  {
    id: "E20",
    source: "N12",
    target: "N03",
    kind: "research",
    label: "High-manganese phosphate cathode pilot",
    weight: 0.52,
    status: "review",
    evidenceId: "S09-C2",
    evidence: "The research institute and Chengyue are conducting a high-manganese phosphate cathode pilot; the production timeline remains undetermined.",
    sourceTitle: "Joint R&D Agreement and Patent Ownership Schedule",
    location: "p.5",
    confidence: 0.82,
    directed: true,
  },
  {
    id: "E21",
    source: "N13",
    target: "N01",
    kind: "certification",
    label: "314Ah cell and battery-pack safety certification",
    weight: 0.57,
    status: "verified",
    evidenceId: "S10-C1",
    evidence: "Jichuan's 314Ah stationary-storage cells and battery packs passed thermal-propagation and cycling-safety tests.",
    sourceTitle: "Anlan Testing Certification Report AL-26-017",
    location: "p.11",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E22",
    source: "N13",
    target: "N05",
    kind: "certification",
    label: "BMS 4.2 functional-safety certification",
    weight: 0.55,
    status: "verified",
    evidenceId: "S10-C2",
    evidence: "Lanxin BMS version 4.2 passed functional-safety and fault-degradation testing.",
    sourceTitle: "Anlan Testing Certification Report AL-26-017",
    location: "p.15",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E23",
    source: "N14",
    target: "N17",
    kind: "support",
    label: "Special funding · RMB 260m",
    weight: 0.78,
    status: "verified",
    evidenceId: "S11-C1",
    evidence: "The Beigang Zero-Carbon Logistics Demonstration Project received RMB 260 million in special funding.",
    sourceTitle: "Donglan New Energy Special Funding Disclosure — Batch I",
    location: "Table 2",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E24",
    source: "N14",
    target: "N18",
    kind: "support",
    label: "Special funding · RMB 120m",
    weight: 0.66,
    status: "verified",
    evidenceId: "S11-C2",
    evidence: "Qingyu Shared Energy Storage Phase I received RMB 120 million in special funding.",
    sourceTitle: "Donglan New Energy Special Funding Disclosure — Batch I",
    location: "Table 2",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E25",
    source: "N06",
    target: "N17",
    kind: "delivery",
    label: "Procurement of 1,200 new energy commercial vehicles",
    weight: 0.88,
    status: "verified",
    evidenceId: "S12-C1",
    evidence: "The Beigang project plan calls for Yaotu to supply 1,200 new energy commercial vehicles.",
    sourceTitle: "Beigang Zero-Carbon Logistics Demonstration Project Implementation Plan",
    location: "p.3, p.9",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E26",
    source: "N01",
    target: "N17",
    kind: "delivery",
    label: "Battery-pack supply · 1.9 GWh",
    weight: 0.86,
    status: "verified",
    evidenceId: "S12-C2",
    evidence: "Jichuan Power will supply 1.9 GWh of battery packs to the Beigang project.",
    sourceTitle: "Beigang Zero-Carbon Logistics Demonstration Project Implementation Plan",
    location: "p.9",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E27",
    source: "N09",
    target: "N17",
    kind: "delivery",
    label: "Five-year fleet operations",
    weight: 0.74,
    status: "verified",
    evidenceId: "S12-C3",
    evidence: "Yuncang Logistics is responsible for five years of fleet operations at the Beigang project.",
    sourceTitle: "Beigang Zero-Carbon Logistics Demonstration Project Implementation Plan",
    location: "p.9",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E28",
    source: "N05",
    target: "N17",
    kind: "delivery",
    label: "Control systems for 48 charging stations",
    weight: 0.7,
    status: "verified",
    evidenceId: "S12-C4",
    evidence: "Lanxin Intelligent Controls will provide control systems for 48 charging stations.",
    sourceTitle: "Beigang Zero-Carbon Logistics Demonstration Project Implementation Plan",
    location: "p.3, p.9",
    confidence: 0.95,
    directed: true,
  },
  {
    id: "E29",
    source: "N07",
    target: "N18",
    kind: "delivery",
    label: "Battery storage system integrator",
    weight: 0.9,
    status: "verified",
    evidenceId: "S13-C1",
    evidence: "Haiyu Energy Storage serves as system integrator for Qingyu Shared Energy Storage Phase I.",
    sourceTitle: "Qingyu Shared Energy Storage Phase I Feasibility Study Summary",
    location: "p.8",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E30",
    source: "N01",
    target: "N18",
    kind: "delivery",
    label: "Stationary-storage cell supply · 0.46 GWh",
    weight: 0.81,
    status: "verified",
    evidenceId: "S13-C2",
    evidence: "Jichuan Power will supply 0.46 GWh of stationary-storage cells to the Qingyu project.",
    sourceTitle: "Qingyu Shared Energy Storage Phase I Feasibility Study Summary",
    location: "p.8",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E31",
    source: "N05",
    target: "N18",
    kind: "delivery",
    label: "EMS / PCS supply",
    weight: 0.77,
    status: "verified",
    evidenceId: "S13-C3",
    evidence: "Lanxin Intelligent Controls will supply the EMS and PCS for the Qingyu project.",
    sourceTitle: "Qingyu Shared Energy Storage Phase I Feasibility Study Summary",
    location: "p.8",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E32",
    source: "N13",
    target: "N18",
    kind: "certification",
    label: "Grid-connection acceptance · pending",
    weight: 0.44,
    status: "review",
    evidenceId: "S13-C4",
    evidence: "Anlan Testing Center is responsible for grid-connection acceptance; commissioning is planned for Q3 2026.",
    sourceTitle: "Qingyu Shared Energy Storage Phase I Feasibility Study Summary",
    location: "p.2, p.8",
    confidence: 0.8,
    directed: true,
  },
];

export const DEMO_SCENES: DemoScene[] = [
  {
    id: "SC01",
    title: "A Single-Core New Energy Ecosystem",
    subtitle: "Jichuan Power connects upstream materials, enabling technologies, capital, and two end-use segments",
    viewMode: "3d",
    layout: "force",
    selectedId: "N01",
    selectedEdgeId: "E02",
    callout: "15 direct relationships and betweenness centrality of 0.41. Both growth and systemic risk are concentrated through Jichuan Power.",
  },
  {
    id: "SC02",
    title: "Three High-Dependency Edges Converge on Core Manufacturing",
    subtitle: "Lithium salts, cathode materials, and control systems combine high concentration with slow substitution",
    viewMode: "3d",
    layout: "radial",
    selectedId: "N01",
    selectedEdgeId: "E05",
    visibleNodes: ["N01", "N02", "N03", "N04", "N05", "N12"],
    visibleKinds: ["supply", "research"],
    callout: "The 36% lithium-salt share, 44% cathode-material share, and 62% BMS coverage apply to different categories and must not be aggregated, but collectively expose insufficient substitution speed.",
  },
  {
    id: "SC03",
    title: "Capital Paths Reach Two Strategic Projects",
    subtitle: "The industrial guidance fund connects critical capabilities to both projects through direct and platform-level investment paths",
    viewMode: "2d",
    layout: "layered",
    selectedId: "N11",
    selectedEdgeId: "E12",
    visibleNodes: ["N01", "N05", "N07", "N10", "N11", "N17", "N18"],
    visibleKinds: ["capital", "delivery"],
    callout: "The shortest association path and the strictly directed capital-to-delivery path are both visible; neither establishes de facto control.",
  },
  {
    id: "SC04",
    title: "RMB 2.76bn Project Pipeline Shares a Common Technology Base",
    subtitle: "Both projects depend on Jichuan Power and Lanxin Intelligent Controls; Qingyu also faces a grid-connection acceptance gate",
    viewMode: "2d",
    layout: "layered",
    selectedId: "N17",
    selectedEdgeId: "E26",
    visibleNodes: ["N01", "N05", "N06", "N07", "N09", "N13", "N14", "N17", "N18"],
    visibleKinds: ["support", "delivery", "certification"],
    callout: "Beigang represents RMB 1.8bn and Qingyu RMB 960m; delays at shared supply nodes would affect both growth trajectories.",
  },
];
