// Completely synthetic demo data. Every organization, person, project, and source below is fictional.

export type NodeKind =
  | "company"
  | "capital"
  | "government"
  | "institution"
  | "person"
  | "project";

export type EdgeKind =
  | "supply"
  | "capital"
  | "governance"
  | "research"
  | "certification"
  | "support"
  | "delivery"
  | "circular";

export interface DemoNode {
  id: string;
  name: string;
  kind: NodeKind;
  subtitle: string;
  x: number;
  y: number;
  z: number;
  summary: string;
  metric: string;
  risk: "high" | "medium" | "low";
  status: "verified" | "review" | "planned";
  sources: string[];
}

export interface DemoEdge {
  id: string;
  source: string;
  target: string;
  kind: EdgeKind;
  label: string;
  weight: number;
  status: "verified" | "review";
  evidenceId: string;
  evidence: string;
  sourceTitle: string;
  location: string;
  confidence: number;
  directed: boolean;
}

export interface DemoScene {
  id: string;
  title: string;
  subtitle: string;
  layout: "force" | "radial" | "layered";
  selectedId: string;
  visibleNodes?: string[];
  visibleKinds?: EdgeKind[];
  callout: string;
}

type DemoSource = {
  id: string;
  title: string;
  date: string;
  type: "经营材料" | "协议" | "项目文件" | "检测报告" | "政策文件" | "分析底稿";
  summary: string;
};

export const DEMO_SOURCES: DemoSource[] = [
  {
    id: "S01",
    title: "《霁川动力 2025 年经营简报》",
    date: "2026-02-28",
    type: "经营材料",
    summary: "披露霁川动力的产能、营收、管理层、主要客户及控制系统覆盖情况。",
  },
  {
    id: "S02",
    title: "《霁川动力股东及关联方清单》",
    date: "2026-01-31",
    type: "经营材料",
    summary: "列示主要股东、管理层持股、研究院关联关系及年度研发投入。",
  },
  {
    id: "S03",
    title: "《核心原材料三年采购框架》",
    date: "2025-09-12",
    type: "协议",
    summary: "汇总锂盐、正极材料和铜箔的供应份额与协议期限。",
  },
  {
    id: "S04",
    title: "《星峪—澄岳供货协议摘要》",
    date: "2025-08-30",
    type: "协议",
    summary: "约定星峪锂源对澄岳新材的最低锂盐供应比例。",
  },
  {
    id: "S05",
    title: "《曜途—霁川年度采购协议》",
    date: "2025-11-05",
    type: "协议",
    summary: "约定新能源商用车动力电池的年度采购规模。",
  },
  {
    id: "S06",
    title: "《海隅储能电芯采购框架》",
    date: "2026-01-08",
    type: "协议",
    summary: "约定海隅储能在 2026 年获得的储能电芯框架额度。",
  },
  {
    id: "S07",
    title: "《电池回收闭环合作备忘录》",
    date: "2026-02-11",
    type: "协议",
    summary: "描述退役电池交付和再生锂盐返供目标。",
  },
  {
    id: "S08",
    title: "《嘉序资本新能源组合复盘》",
    date: "2026-01-10",
    type: "经营材料",
    summary: "披露嘉序资本的新能源持仓、管理团队与锚定出资人。",
  },
  {
    id: "S09",
    title: "《联合研发协议与专利归属表》",
    date: "2025-08-22",
    type: "协议",
    summary: "记录 BMS 算法与高锰磷酸盐正极材料的联合研发安排。",
  },
  {
    id: "S10",
    title: "《安澜检测认证报告 AL-26-017》",
    date: "2026-03-01",
    type: "检测报告",
    summary: "覆盖储能电芯、电池包及 BMS 的安全和故障降级测试。",
  },
  {
    id: "S11",
    title: "《东澜新能源专项资金公示（第一批）》",
    date: "2026-02-05",
    type: "政策文件",
    summary: "公示北港零碳物流和青屿共享储能项目的专项支持金额。",
  },
  {
    id: "S12",
    title: "《北港零碳物流示范项目实施方案》",
    date: "2026-01-15",
    type: "项目文件",
    summary: "列示项目规模、车辆、补能站、供应商及运营分工。",
  },
  {
    id: "S13",
    title: "《青屿共享储能一期可研摘要》",
    date: "2025-12-20",
    type: "项目文件",
    summary: "列示储能规模、投资、计划投运时间和主要交付方。",
  },
  {
    id: "S14",
    title: "《供应链压力测试与替代性评估》",
    date: "2026-03-22",
    type: "分析底稿",
    summary: "评估关键供应商替代周期、关键性评分和网络中心性。",
  },
  {
    id: "S15",
    title: "《新能源生态主体核验表》",
    date: "2026-03-25",
    type: "分析底稿",
    summary: "汇总上游产能、下游交付规模、基金规模与机构能力。",
  },
];

export const DEMO_NODES: DemoNode[] = [
  {
    id: "N01",
    name: "霁川动力",
    kind: "company",
    subtitle: "动力与储能电芯核心制造商",
    x: 0,
    y: 0,
    z: 0,
    summary: "连接上游材料、控制系统、资本与两类应用场景，是生态中的单核枢纽。",
    metric: "24 GWh · 营收 48.6 亿元",
    risk: "high",
    status: "verified",
    sources: ["S01", "S02", "S14"],
  },
  {
    id: "N02",
    name: "星峪锂源",
    kind: "company",
    subtitle: "电池级锂盐供应商",
    x: -25,
    y: 12,
    z: -4,
    summary: "同时向霁川动力和澄岳新材供货，替代周期较长。",
    metric: "产能 4.5 万吨 · 关键性 4.6",
    risk: "high",
    status: "verified",
    sources: ["S03", "S04", "S14", "S15"],
  },
  {
    id: "N03",
    name: "澄岳新材",
    kind: "company",
    subtitle: "正极材料供应商",
    x: -17,
    y: 5,
    z: 2,
    summary: "霁川动力第一大正极材料来源，并参与下一代材料中试。",
    metric: "产能 12 万吨 · 采购占比 44%",
    risk: "high",
    status: "verified",
    sources: ["S03", "S09", "S14", "S15"],
  },
  {
    id: "N04",
    name: "衡岭铜箔",
    kind: "company",
    subtitle: "电池铜箔供应商",
    x: -20,
    y: -7,
    z: -2,
    summary: "为霁川动力提供动力电池铜箔，集中度处于中等水平。",
    metric: "产能 6.5 万吨 · 采购占比 31%",
    risk: "medium",
    status: "verified",
    sources: ["S03", "S15"],
  },
  {
    id: "N05",
    name: "岚芯智控",
    kind: "company",
    subtitle: "BMS、EMS 与 PCS 提供商",
    x: -2,
    y: 14,
    z: 5,
    summary: "同时覆盖电池生产、物流补能与共享储能项目，是关键控制系统节点。",
    metric: "覆盖 62% 在产电池包",
    risk: "high",
    status: "verified",
    sources: ["S01", "S08", "S09", "S10", "S14"],
  },
  {
    id: "N06",
    name: "曜途商用车",
    kind: "company",
    subtitle: "新能源商用车整车厂",
    x: 21,
    y: 8,
    z: 4,
    summary: "霁川动力最大的动力电池框架客户，也是北港项目的整车交付方。",
    metric: "年产能 2.8 万辆",
    risk: "medium",
    status: "verified",
    sources: ["S05", "S12", "S15"],
  },
  {
    id: "N07",
    name: "海隅储能",
    kind: "company",
    subtitle: "储能系统集成商",
    x: 20,
    y: -5,
    z: 0,
    summary: "承担青屿项目系统集成，并持有霁川储能电芯框架额度。",
    metric: "累计交付 2.1 GWh",
    risk: "medium",
    status: "verified",
    sources: ["S06", "S08", "S13", "S15"],
  },
  {
    id: "N08",
    name: "循光资源",
    kind: "company",
    subtitle: "退役电池回收企业",
    x: -11,
    y: -16,
    z: 5,
    summary: "承接霁川退役电池，并计划以再生锂盐形成材料闭环。",
    metric: "回收能力 5 万吨/年",
    risk: "medium",
    status: "verified",
    sources: ["S07", "S15"],
  },
  {
    id: "N09",
    name: "云沧物流",
    kind: "company",
    subtitle: "商用车队运营商",
    x: 25,
    y: 16,
    z: -3,
    summary: "负责北港项目五年车队运营，是项目需求兑现的直接观察点。",
    metric: "运营车辆 1.8 万辆",
    risk: "low",
    status: "verified",
    sources: ["S12", "S15"],
  },
  {
    id: "N10",
    name: "嘉序资本",
    kind: "capital",
    subtitle: "新能源产业投资机构",
    x: 0,
    y: -21,
    z: 7,
    summary: "投资横跨电芯、控制系统与储能集成，形成跨环节资本影响路径。",
    metric: "管理规模 120 亿元",
    risk: "medium",
    status: "verified",
    sources: ["S02", "S08", "S15"],
  },
  {
    id: "N11",
    name: "东澜产业引导基金",
    kind: "capital",
    subtitle: "政府产业引导基金",
    x: -9,
    y: -29,
    z: 2,
    summary: "既直接投资霁川动力，也作为嘉序新能源基金的锚定出资人。",
    metric: "基金规模 200 亿元",
    risk: "low",
    status: "verified",
    sources: ["S02", "S08", "S15"],
  },
  {
    id: "N12",
    name: "霁川先进电池研究院",
    kind: "institution",
    subtitle: "电池技术联合研发平台",
    x: -9,
    y: 22,
    z: 7,
    summary: "连接霁川、岚芯与澄岳，承担控制算法和新材料中试。",
    metric: "37 项有效专利",
    risk: "low",
    status: "verified",
    sources: ["S02", "S09", "S15"],
  },
  {
    id: "N13",
    name: "安澜检测中心",
    kind: "institution",
    subtitle: "电池与并网检测机构",
    x: 11,
    y: 22,
    z: -4,
    summary: "承担电芯、控制系统检测及青屿项目并网验收。",
    metric: "覆盖 3 类关键认证",
    risk: "low",
    status: "verified",
    sources: ["S10", "S13"],
  },
  {
    id: "N14",
    name: "东澜新能源促进局",
    kind: "government",
    subtitle: "产业推进与项目资金机构",
    x: 19,
    y: -23,
    z: -3,
    summary: "通过专项资金同时支持物流电动化与共享储能项目。",
    metric: "专项支持 3.8 亿元",
    risk: "low",
    status: "verified",
    sources: ["S11"],
  },
  {
    id: "N15",
    name: "沈砚舟",
    kind: "person",
    subtitle: "霁川动力董事长兼 CEO",
    x: 8,
    y: -13,
    z: 11,
    summary: "同时担任研究院理事长，连接公司治理与研发资源。",
    metric: "持股 6.5%",
    risk: "medium",
    status: "verified",
    sources: ["S01", "S02"],
  },
  {
    id: "N16",
    name: "林见微",
    kind: "person",
    subtitle: "嘉序资本管理合伙人",
    x: 4,
    y: -31,
    z: 9,
    summary: "负责嘉序新能源投资组合的配置与投后管理。",
    metric: "覆盖 3 个生态关键节点",
    risk: "low",
    status: "verified",
    sources: ["S08"],
  },
  {
    id: "N17",
    name: "北港零碳物流示范项目",
    kind: "project",
    subtitle: "新能源商用车与补能网络",
    x: 34,
    y: 9,
    z: 8,
    summary: "整合整车、电池、控制系统与车队运营的区域示范项目。",
    metric: "18 亿元 · 1200 辆 · 48 站",
    risk: "medium",
    status: "planned",
    sources: ["S11", "S12"],
  },
  {
    id: "N18",
    name: "青屿共享储能一期",
    kind: "project",
    subtitle: "区域共享储能电站",
    x: 34,
    y: -9,
    z: -7,
    summary: "由海隅集成、霁川与岚芯供货，投运前仍需完成并网验收。",
    metric: "200 MW / 400 MWh · 9.6 亿元",
    risk: "medium",
    status: "planned",
    sources: ["S11", "S13"],
  },
];

export const DEMO_EDGES: DemoEdge[] = [
  {
    id: "E01",
    source: "N02",
    target: "N03",
    kind: "supply",
    label: "锂盐供应 · 55%",
    weight: 0.82,
    status: "verified",
    evidenceId: "S04-C1",
    evidence: "2025—2027 年，星峪承诺满足澄岳不低于 55% 的电池级锂盐需求。",
    sourceTitle: "《星峪—澄岳供货协议摘要》",
    location: "§2",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E02",
    source: "N02",
    target: "N01",
    kind: "supply",
    label: "直接锂盐供应 · 36%",
    weight: 0.86,
    status: "verified",
    evidenceId: "S03-C1",
    evidence: "星峪锂源约占霁川动力电池级锂盐年度采购量 36%。",
    sourceTitle: "《核心原材料三年采购框架》",
    location: "p.4",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E03",
    source: "N03",
    target: "N01",
    kind: "supply",
    label: "正极材料供应 · 44%",
    weight: 0.91,
    status: "verified",
    evidenceId: "S03-C2",
    evidence: "澄岳新材占霁川动力正极材料采购量 44%。",
    sourceTitle: "《核心原材料三年采购框架》",
    location: "p.5",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E04",
    source: "N04",
    target: "N01",
    kind: "supply",
    label: "铜箔供应 · 31%",
    weight: 0.72,
    status: "verified",
    evidenceId: "S03-C3",
    evidence: "衡岭铜箔占霁川动力电池铜箔采购量 31%。",
    sourceTitle: "《核心原材料三年采购框架》",
    location: "p.5",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E05",
    source: "N05",
    target: "N01",
    kind: "supply",
    label: "BMS 控制器 · 覆盖 62%",
    weight: 0.94,
    status: "verified",
    evidenceId: "S01-C2",
    evidence: "岚芯智控控制器覆盖霁川动力 62% 的在产电池包。",
    sourceTitle: "《霁川动力 2025 年经营简报》",
    location: "p.7 §3.2",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E06",
    source: "N01",
    target: "N06",
    kind: "supply",
    label: "动力电池 · 8 GWh/年",
    weight: 0.95,
    status: "verified",
    evidenceId: "S05-C1",
    evidence: "曜途计划每年向霁川采购不低于 8 GWh 商用车动力电池。",
    sourceTitle: "《曜途—霁川年度采购协议》",
    location: "§3",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E07",
    source: "N01",
    target: "N07",
    kind: "supply",
    label: "储能电芯 · 3.2 GWh/年",
    weight: 0.8,
    status: "verified",
    evidenceId: "S06-C1",
    evidence: "海隅获得霁川 2026 年度最高 3.2 GWh 储能电芯框架额度。",
    sourceTitle: "《海隅储能电芯采购框架》",
    location: "§2",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E08",
    source: "N01",
    target: "N08",
    kind: "circular",
    label: "退役电池优先回收",
    weight: 0.61,
    status: "verified",
    evidenceId: "S07-C1",
    evidence: "霁川将符合条件的退役电池优先交由循光资源拆解处理。",
    sourceTitle: "《电池回收闭环合作备忘录》",
    location: "§2",
    confidence: 0.94,
    directed: true,
  },
  {
    id: "E09",
    source: "N08",
    target: "N01",
    kind: "circular",
    label: "再生锂盐返供 · 目标 20%",
    weight: 0.48,
    status: "review",
    evidenceId: "S07-C2",
    evidence: "双方目标为 2027 年前由循光返供的再生锂盐覆盖霁川需求的 20%。",
    sourceTitle: "《电池回收闭环合作备忘录》",
    location: "§4",
    confidence: 0.79,
    directed: true,
  },
  {
    id: "E10",
    source: "N10",
    target: "N01",
    kind: "capital",
    label: "直接持股 12.4%",
    weight: 0.79,
    status: "verified",
    evidenceId: "S02-C1",
    evidence: "嘉序资本持有霁川动力 12.4% 股权。",
    sourceTitle: "《霁川动力股东及关联方清单》",
    location: "p.3",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E11",
    source: "N11",
    target: "N01",
    kind: "capital",
    label: "直接持股 8.0%",
    weight: 0.65,
    status: "verified",
    evidenceId: "S02-C2",
    evidence: "东澜产业引导基金持有霁川动力 8.0% 股权。",
    sourceTitle: "《霁川动力股东及关联方清单》",
    location: "p.3",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E12",
    source: "N11",
    target: "N10",
    kind: "capital",
    label: "锚定 LP · 认缴 24%",
    weight: 0.76,
    status: "verified",
    evidenceId: "S08-C2",
    evidence: "东澜产业引导基金认缴嘉序新能源基金 24% 的基金份额。",
    sourceTitle: "《嘉序资本新能源组合复盘》",
    location: "p.2",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E13",
    source: "N10",
    target: "N05",
    kind: "capital",
    label: "直接持股 18%",
    weight: 0.83,
    status: "verified",
    evidenceId: "S08-C1",
    evidence: "嘉序资本持有岚芯智控 18% 股权。",
    sourceTitle: "《嘉序资本新能源组合复盘》",
    location: "p.6",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E14",
    source: "N10",
    target: "N07",
    kind: "capital",
    label: "直接持股 9%",
    weight: 0.62,
    status: "verified",
    evidenceId: "S08-C3",
    evidence: "嘉序资本持有海隅储能 9% 股权。",
    sourceTitle: "《嘉序资本新能源组合复盘》",
    location: "p.6",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E15",
    source: "N15",
    target: "N01",
    kind: "governance",
    label: "董事长兼 CEO · 持股 6.5%",
    weight: 0.92,
    status: "verified",
    evidenceId: "S01-C1",
    evidence: "沈砚舟任霁川动力董事长兼 CEO，并持有公司 6.5% 股权。",
    sourceTitle: "《霁川动力 2025 年经营简报》",
    location: "p.2 §1.1",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E16",
    source: "N16",
    target: "N10",
    kind: "governance",
    label: "管理合伙人",
    weight: 0.73,
    status: "verified",
    evidenceId: "S08-C4",
    evidence: "林见微任嘉序资本管理合伙人。",
    sourceTitle: "《嘉序资本新能源组合复盘》",
    location: "p.6",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E17",
    source: "N15",
    target: "N12",
    kind: "governance",
    label: "研究院理事长",
    weight: 0.64,
    status: "verified",
    evidenceId: "S02-C3",
    evidence: "沈砚舟兼任霁川先进电池研究院理事长。",
    sourceTitle: "《霁川动力股东及关联方清单》",
    location: "p.8",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E18",
    source: "N01",
    target: "N12",
    kind: "research",
    label: "研发经费 6000 万元/年",
    weight: 0.71,
    status: "verified",
    evidenceId: "S02-C4",
    evidence: "霁川动力每年向研究院提供 6000 万元研发经费。",
    sourceTitle: "《霁川动力股东及关联方清单》",
    location: "p.8",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E19",
    source: "N12",
    target: "N05",
    kind: "research",
    label: "联合开发车储协同 BMS",
    weight: 0.68,
    status: "verified",
    evidenceId: "S09-C1",
    evidence: "研究院与岚芯共同开发车储协同 BMS 算法，阶段样机已完成。",
    sourceTitle: "《联合研发协议与专利归属表》",
    location: "p.3",
    confidence: 0.94,
    directed: true,
  },
  {
    id: "E20",
    source: "N12",
    target: "N03",
    kind: "research",
    label: "高锰磷酸盐正极中试",
    weight: 0.52,
    status: "review",
    evidenceId: "S09-C2",
    evidence: "研究院与澄岳开展高锰磷酸盐正极中试，量产时间尚未确定。",
    sourceTitle: "《联合研发协议与专利归属表》",
    location: "p.5",
    confidence: 0.82,
    directed: true,
  },
  {
    id: "E21",
    source: "N13",
    target: "N01",
    kind: "certification",
    label: "314Ah 电芯及电池包安全认证",
    weight: 0.57,
    status: "verified",
    evidenceId: "S10-C1",
    evidence: "霁川 314Ah 储能电芯及电池包通过热扩散与循环安全测试。",
    sourceTitle: "《安澜检测认证报告 AL-26-017》",
    location: "p.11",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E22",
    source: "N13",
    target: "N05",
    kind: "certification",
    label: "BMS 4.2 功能安全认证",
    weight: 0.55,
    status: "verified",
    evidenceId: "S10-C2",
    evidence: "岚芯 BMS 4.2 版本通过功能安全与故障降级测试。",
    sourceTitle: "《安澜检测认证报告 AL-26-017》",
    location: "p.15",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E23",
    source: "N14",
    target: "N17",
    kind: "support",
    label: "专项资金 2.6 亿元",
    weight: 0.78,
    status: "verified",
    evidenceId: "S11-C1",
    evidence: "北港零碳物流示范项目获得专项资金支持 2.6 亿元。",
    sourceTitle: "《东澜新能源专项资金公示（第一批）》",
    location: "表 2",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E24",
    source: "N14",
    target: "N18",
    kind: "support",
    label: "专项资金 1.2 亿元",
    weight: 0.66,
    status: "verified",
    evidenceId: "S11-C2",
    evidence: "青屿共享储能一期获得专项资金支持 1.2 亿元。",
    sourceTitle: "《东澜新能源专项资金公示（第一批）》",
    location: "表 2",
    confidence: 0.99,
    directed: true,
  },
  {
    id: "E25",
    source: "N17",
    target: "N06",
    kind: "delivery",
    label: "采购 1200 辆新能源商用车",
    weight: 0.88,
    status: "verified",
    evidenceId: "S12-C1",
    evidence: "北港项目规划由曜途供应 1200 辆新能源商用车。",
    sourceTitle: "《北港零碳物流示范项目实施方案》",
    location: "p.3、p.9",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E26",
    source: "N17",
    target: "N01",
    kind: "delivery",
    label: "配套 1.9 GWh 电池包",
    weight: 0.86,
    status: "verified",
    evidenceId: "S12-C2",
    evidence: "霁川动力为北港项目提供 1.9 GWh 电池包。",
    sourceTitle: "《北港零碳物流示范项目实施方案》",
    location: "p.9",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E27",
    source: "N09",
    target: "N17",
    kind: "delivery",
    label: "五年车队运营",
    weight: 0.74,
    status: "verified",
    evidenceId: "S12-C3",
    evidence: "云沧物流负责北港项目五年期车队运营。",
    sourceTitle: "《北港零碳物流示范项目实施方案》",
    location: "p.9",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E28",
    source: "N05",
    target: "N17",
    kind: "delivery",
    label: "48 座补能站控制系统",
    weight: 0.7,
    status: "verified",
    evidenceId: "S12-C4",
    evidence: "岚芯智控为 48 座补能站提供控制系统。",
    sourceTitle: "《北港零碳物流示范项目实施方案》",
    location: "p.3、p.9",
    confidence: 0.95,
    directed: true,
  },
  {
    id: "E29",
    source: "N07",
    target: "N18",
    kind: "delivery",
    label: "储能系统集成方",
    weight: 0.9,
    status: "verified",
    evidenceId: "S13-C1",
    evidence: "海隅储能担任青屿共享储能一期系统集成方。",
    sourceTitle: "《青屿共享储能一期可研摘要》",
    location: "p.8",
    confidence: 0.98,
    directed: true,
  },
  {
    id: "E30",
    source: "N01",
    target: "N18",
    kind: "delivery",
    label: "供应 0.46 GWh 储能电芯",
    weight: 0.81,
    status: "verified",
    evidenceId: "S13-C2",
    evidence: "霁川动力为青屿项目供应 0.46 GWh 储能电芯。",
    sourceTitle: "《青屿共享储能一期可研摘要》",
    location: "p.8",
    confidence: 0.97,
    directed: true,
  },
  {
    id: "E31",
    source: "N05",
    target: "N18",
    kind: "delivery",
    label: "供应 EMS / PCS",
    weight: 0.77,
    status: "verified",
    evidenceId: "S13-C3",
    evidence: "岚芯智控为青屿项目供应 EMS 与 PCS。",
    sourceTitle: "《青屿共享储能一期可研摘要》",
    location: "p.8",
    confidence: 0.96,
    directed: true,
  },
  {
    id: "E32",
    source: "N13",
    target: "N18",
    kind: "certification",
    label: "并网验收 · 尚未完成",
    weight: 0.44,
    status: "review",
    evidenceId: "S13-C4",
    evidence: "安澜检测中心承担并网验收，项目计划于 2026 年第三季度投运。",
    sourceTitle: "《青屿共享储能一期可研摘要》",
    location: "p.2、p.8",
    confidence: 0.8,
    directed: true,
  },
];

export const DEMO_SCENES: DemoScene[] = [
  {
    id: "SC01",
    title: "单核驱动的新能源生态",
    subtitle: "霁川动力同时连接上游材料、技术配套、资本与两类应用场景",
    layout: "force",
    selectedId: "N01",
    callout: "14 条直接关系，介数中心性 0.41。增长与系统性风险均集中经过霁川动力。",
  },
  {
    id: "SC02",
    title: "三条高依赖边集中于核心制造环节",
    subtitle: "锂盐、正极材料与控制系统均存在七个月以上替代周期",
    layout: "radial",
    selectedId: "N01",
    visibleNodes: ["N01", "N02", "N03", "N04", "N05", "N12"],
    visibleKinds: ["supply", "research"],
    callout: "36% 锂盐、44% 正极材料、62% BMS 覆盖属于不同品类，不应相加，但共同暴露替代速度不足。",
  },
  {
    id: "SC03",
    title: "一条资本链覆盖三项关键能力",
    subtitle: "产业引导基金经由嘉序资本连接电芯、控制系统与储能集成",
    layout: "layered",
    selectedId: "N10",
    visibleNodes: ["N01", "N05", "N07", "N10", "N11", "N12", "N15", "N16"],
    visibleKinds: ["capital", "governance", "research"],
    callout: "资本结构可能提升协同效率，也会放大融资与治理变化的跨环节传导；持股不等同于实际控制。",
  },
  {
    id: "SC04",
    title: "27.6 亿元项目储备共享同一技术底座",
    subtitle: "两个项目均依赖霁川动力和岚芯智控，青屿项目另有并网验收门槛",
    layout: "layered",
    selectedId: "N17",
    visibleNodes: ["N01", "N05", "N06", "N07", "N09", "N13", "N14", "N17", "N18"],
    visibleKinds: ["support", "delivery", "certification"],
    callout: "北港项目 18 亿元、青屿项目 9.6 亿元；共同供应节点延期会同时影响两条增长曲线。",
  },
];
